fix: fetch all repos for top languages
anuraghazra/github-readme-stats pull request #1178
Opened 2021-07-08 08:42 UTC by tc-imba

This fixed #1177

2021-07-18 09:19 UTC, tc-imba commented
@anuraghazra any comments?

2022-07-12 17:53 UTC, IamManchanda commented
any updates to this?

2022-09-16 11:14 UTC, Jordhan-Carvalho commented
My status is off by a considerable margin because of this, please give it some attention since it`s a critical bug for the cards

2022-09-16 11:58 UTC, rickstaa commented
@Jordhan-Carvalho Thanks for your comment. We sadly did not have the time to look at this pull request, but we are aware of the problem (see #1852 and #1801). To get this feature implemented quicker, people can best show their support by giving a 👍🏻 to #1178 and #1801. This way, it is pushed higher in the [Top features dashboard](https://github.com/anuraghazra/github-readme-stats/issues/1935).

2022-09-17 11:24 UTC, rickstaa requested changes

2022-09-17 11:24 UTC, rickstaa commented on src/fetchers/top-languages-fetcher.js
> +  const pageSize = 100;
Maybe we can use the [pageInfo](https://docs.github.com/en/graphql/reference/objects#pageinfo) object to get cleaner code. 🚀 

```js
  // Loop through all pages and fetch all repos
  let repoNodes = [];
  let hasNextPage = true
  let endCursor = null
  while (hasNextPage) {
      const variables = { login: username, first: 100, after: endCursor };
      const res = await retryer(fetcher, variables);
      
      if (res.data.errors) {
        logger.error(res.data.errors);
        throw Error(res.data.errors[0].message || "Could not fetch user");
      }
      
      repoNodes.push(...res.data.data.user.repositories.nodes);
      hasNextPage = res.data.data.user.repositories.pageInfo.hasNextPage
      endCursor = res.data.data.user.repositories.pageInfo.endCursor
  }
```

2022-09-17 11:26 UTC, rickstaa commented
@tc-imba, @Jordhan-Carvalho, I found some time today to review this pull request. Overall it looks good to me! 🚀 I would, however, use the [pageInfo](https://docs.github.com/en/graphql/reference/objects#pageinfo) object to get cleaner code. @tc-imba is there a reason you are using the cursor instead?

2022-10-08 10:23 UTC, rickstaa commented
replaced by #2111.

2022-10-08 10:23 UTC, closed without merging