add
anuraghazra/github-readme-stats pull request #1309
Opened 2021-09-12 19:01 UTC by arunt7767

added a new theme
 name: "Neon Knights"
''' I'm just learning how to contribute to open source

2021-09-12 19:02 UTC, anuraghazra commented
Theme preview (bot)  
      
      
title_color: <code>#00FF00</code> | icon_color: <code>#00FF00</code> | text_color: <code>#ffffff</code> | bg_color: <code>#000000</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=00FF00&icon_color=00FF00&text_color=ffffff&bg_color=000000&show_icons=true

      
[![](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=00FF00&icon_color=00FF00&text_color=ffffff&bg_color=000000&show_icons=true)](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=00FF00&icon_color=00FF00&text_color=ffffff&bg_color=000000&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

2021-09-12 19:02 UTC, arunt7767 commented
#first

2021-09-12 19:14 UTC, arunt7767 commented
ok 👍

2022-10-02 15:23 UTC, rickstaa requested changes

2022-10-02 15:23 UTC, rickstaa commented on themes/index.js
> +  Neon Knights : {
Invalid json syntax.

2022-10-02 15:23 UTC, closed without merging