Fix #1170: Allow customizable width for GitHub Stats Card
anuraghazra/github-readme-stats pull request #1334
Opened 2021-09-28 07:51 UTC by postatum

Fixes #1170 by allowing customizable width for Github Stats Card.

To avoid things overlaping each other, Stats Card has minimum widths which are applied when provided `custom_width` is less than certain values.

2021-11-04 09:53 UTC, rickstaa commented
@postatum Thanks for your pull request. I quickly reviewed your code and it looks good to me. It however looks that the current code doesn't take into account the `show_icons` argument (see last example below). You might have to reload several times to see all the stats since Github will likely timeout trying to request so many stats at the same time.

### hide_rank=true

#### Test without card_width

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&hide_rank=true)

#### Test with to small card_width (i.e 50)

This card width is `220` px smaller than the minimum card width of `270` px.

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&hide_rank=true&card_width=50)

#### Test with card_width 300 

This card width is `30` px bigger than the minimum card width of `270`.

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&hide_rank=true&card_width=300)

####  Test with card_width 600

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&hide_rank=true&card_width=600)

### hide_rank=true, show_icons=true

#### Test without card_width

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&show_icons=true&hide_rank=true)

#### Test with to small card_width (i.e 50)

This card width is `220` px smaller than the minimum card width of `270` px.

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&show_icons=true&hide_rank=true&card_width=50)

#### Test with card_width 300 

This card width is `30` px bigger than the minimum card width of `270`.

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&show_icons=true&hide_rank=true&card_width=300)

####  Test with card_width 600

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&show_icons=true&hide_rank=true&card_width=600)

### hide_rank=false

#### Test without card_width

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&hide_rank=false)

#### Test with to small card_width (i.e 50)

This card width is `220` px smaller than the minimum card width of `270` px.

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&hide_rank=false&card_width=50)

#### Test with card_width 300 

This card width is `30` px bigger than the minimum card width of `270`.

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&hide_rank=false&card_width=300)

####  Test with card_width 600

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&hide_rank=false&card_width=600)

### hide_rank=false, show_icons=true

#### Test without card_width

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&show_icons=true&hide_rank=false)

#### Test with to small card_width (i.e 50)

This card width is `220` px smaller than the minimum card width of `270` px.

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&show_icons=true&hide_rank=false&card_width=50)

#### Test with card_width 300 

This card width is `30` px bigger than the minimum card width of `270`.

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&show_icons=true&hide_rank=false&card_width=300)

####  Test with card_width 600

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix-rickstaa.vercel.app/api?username=rickstaa&show_icons=true&hide_rank=false&card_width=600)

2021-11-04 09:54 UTC, rickstaa commented on src/cards/stats-card.js
>          50 /* padding */ + calculateTextWidth() * 2,
I think here you should also take into account the icon width when the `hide_icons` flag is set to `false`.

2021-11-04 09:56 UTC, rickstaa commented on src/cards/stats-card.js
> +    When hide_rank=true, minimum card width is max of 270 and length of title + paddings.
Maybe change this to:

```text 
When hide_rank=true, the minimum card width is 270 px plus the length of title and paddings.
```

The `max` confused me a bit.

2021-11-04 10:11 UTC, rickstaa commented
@postatum, please see https://github.com/postatum/github-readme-stats/pull/1/files for a fix to the issue described above. It also trims trialling whitespace, but I can remove that if you want.

2021-11-04 10:36 UTC, rickstaa requested changes

2021-11-04 10:36 UTC, rickstaa commented on src/cards/stats-card.js
> +    When hide_rank=true, minimum card width is max of 270 and length of title + paddings.
Maybe change this to:

```text
When hide_rank=true, the minimum card width is 270 px + the title length and padding.
When hide_rank=false, the minimum card_width is 340 px + the icon width (if show_icons=true).
Numbers are picked by looking at existing dimensions on production.
```

The ``max`` in your old description confused me a bit.

2021-11-04 10:36 UTC, rickstaa commented on src/cards/stats-card.js
> +    : 340
I think here you should also take into account the icon width when the show_icons flag is set to true. This is 16 px. Please merge https://github.com/postatum/github-readme-stats/pull/1 to fix this issue.

2021-11-04 13:37 UTC, anuraghazra commented
The rank circle looks like shifted way too much to the right on the new updates 

Left: THIS PR
Right: CURRENT
![image](https://user-images.githubusercontent.com/35374649/140322991-a63eebe5-2c94-4c82-8715-387436caaaad.png)

2021-11-04 17:11 UTC, rickstaa commented
@anuraghazra You are right I missed that. This seems to be caused by the following code that was added by @postatum:

https://github.com/anuraghazra/github-readme-stats/blob/dc78bad925e57ac875e9da435c546c1c4a63ab97/src/cards/stats-card.js#L230

I added a fix for this to my pull request.

#### Test with to small card_width (i.e 50)

This card width is `220` px smaller than the minimum card width of `270` px.

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix2-rickstaa.vercel.app/api?username=rickstaa&show_icons=true&hide_rank=false&card_width=50)

#### Test with card_width 300 

This card width is `30` px bigger than the minimum card width of `270`.

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix2-rickstaa.vercel.app/api?username=rickstaa&show_icons=true&hide_rank=false&card_width=300)

####  Test with card_width 600

![Rick Staa's GitHub stats](https://github-readme-stats-git-testwidthfix2-rickstaa.vercel.app/api?username=rickstaa&show_icons=true&hide_rank=false&card_width=600)

2021-11-04 17:19 UTC, rickstaa commented
Left: THIS PR https://github-readme-stats-git-testwidthfix2-rickstaa.vercel.app/api?username=anuraghazra&show_icons=true&hide_rank=false
Right: CURRENT https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&hide_rank=false

| <a href="https://github.com/anuraghazra/github-readme-stats"><img align="center" src="https://github-readme-stats-git-testwidthfix2-rickstaa.vercel.app/api?username=anuraghazra&show_icons=true&hide_rank=false" alt="Anurag's github stats" /></a> | <a href="https://github.com/anuraghazra/github-readme-stats"><img align="center" src="https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&hide_rank=false" /></a> |
| ------------- | ------------- |

2021-11-06 13:29 UTC, anuraghazra commented
@postatum can you merge in the changes done by @rickstaa? 

Also @rickstaa it's better to keep the PR waterfall minimal, try to code review the PR first instead of committing to the branch of Artem.

2021-11-06 22:48 UTC, rickstaa commented
@anuraghazra No problem, I will do that next time. I created the pull request to speed up the development process since it solves one of my problems.

2021-11-08 05:47 UTC, postatum commented
Hi guys!

Thanks for reviewing this PR. Sorry, I didn't have time to merge your PR. I did it just now.

2021-11-08 11:41 UTC, rickstaa commented
@postatum No problem. Thanks again for creating this pull request!

2021-11-08 22:35 UTC, rickstaa requested changes

2021-11-08 22:35 UTC, rickstaa commented on tests/renderStatsCard.test.js
> +    expect(document.querySelector("svg")).toHaveAttribute("width", "305.81250000000006");
@postatum It looks like the current card width with this setting should be 270 px.

![Rick Staa's Github stats](https://github-readme-stats-taupe-pi.vercel.app/api?username=rickstaa&card_width=1&hide_rank=true)

2021-11-08 22:35 UTC, rickstaa commented on tests/renderStatsCard.test.js
> +    document.body.innerHTML = renderStatsCard(stats, { card_width: 1, hide_rank: true });
@postatum Maybe we should also add tests for the `show_icons` option. My commit now adds `16px` when this option is enabled.

![Rick's Github Stats](https://github-readme-stats-taupe-pi.vercel.app/api?username=rickstaa&card_width=1&hide_rank=true&show_icons=true)

2021-11-08 22:40 UTC, rickstaa requested changes

2021-11-08 22:40 UTC, rickstaa commented on src/cards/stats-card.js
> +  const defaultCardWidth = hide_rank ? 270 : 495;
@postatum, @anuraghazra Maybe we should also add the `iconWidth` to the `minwidth` of the card when `hide_rank=true`. By doing this the behaviour for the `hide_icons` option is similar to the case where `hide_rank=false`.

```js
const defaultCardWidth = hide_rank ? 270 + show_icons : 495;
```

2022-05-01 03:43 UTC, douglasg14b commented
Is this blocked by code review mostly?

2022-05-01 19:18 UTC, rickstaa commented
@douglasg14b Thanks for your interest in this feature. I already reviewed this PR some time ago. I, however, have to check it one last time. There are currently three things preventing this PR from being merged:

    1. https://github.com/anuraghazra/github-readme-stats/pull/1334#discussion_r745146226: A test for the `show_icons` needs to be added.
    2. I did to receive a reaction yet from @anuraghazra and @postatum about https://github.com/anuraghazra/github-readme-stats/pull/1334#discussion_r745148745. I am happy to implement this change, but some feedback would be excellent.
    3. I need to rebase this on top of the main branch. This needs to be carefully done since #1628 changed the code also altered in this PR.

After these points are solved, this PR can be merged. However, I am very short on time since I'm in the final stage of my master's thesis. Therefore, I cannot make a promise when I have time to look at this PR again.

2022-09-16 10:50 UTC, merged

2022-09-16 10:52 UTC, rickstaa commented
Sorry for the delay but I just merged this into the master. @postatum Thanks a lot for implementing this feature 🚀.