Updated readme_de.md
anuraghazra/github-readme-stats pull request #1462
Opened 2021-11-16 18:21 UTC by ollo-der-echte

There were some spelling issues, but probably it's all right as it was last version, what do you think?

2021-11-16 18:44 UTC, Morphclue requested changes
I think these changes would be benefitial.

2021-11-16 18:44 UTC, Morphclue commented on docs/readme_de.md
> +- `range` – Fragt eine Zeitspanne an, als die standardmäßig in WakaTime hinterlegte, z.B. `last_7_days`. Siehe [WakaTime API Dokumentation](https://wakatime.com/developers#stats).
```suggestion
- `range` – Fragt eine andere Zeitspanne an, als jene, welche standardmäßig in Wakatime hinterlegt ist. Zum Beispiel `last_7_days`. Siehe [WakaTime API Dokumentation](https://wakatime.com/developers#stats).
```

2021-11-16 18:44 UTC, Morphclue commented on docs/readme_de.md
> +1. Klicke auf "Deploy", und das wars. Besuche deine Domains um die API zu benutzen!
```suggestion
1. Klicke auf `Deploy`, und das wars. Besuche deine Domains um die API zu benutzen!
```

2021-11-16 20:35 UTC, ollo-der-echte commented on docs/readme_de.md
> +1. Klicke auf "Deploy", und das wars. Besuche deine Domains um die API zu benutzen!
Yea, that's way better, I'm sorry

2021-11-17 00:06 UTC, w3bdesign approved these changes

2022-05-03 16:41 UTC, Morphclue approved these changes

2022-05-04 07:33 UTC, rickstaa commented
@Morphclue thanks for reviewing this PR. Now it has the two reviews required for merging translation-related PRs. I merged it into the main branch.

2022-05-04 07:34 UTC, merged