chore: replace `git.io` links
anuraghazra/github-readme-stats pull request #1724
Opened 2022-04-27 13:59 UTC by SukkaW

All links on git.io will stop redirecting after April 29, 2022: https://github.blog/changelog/2022-04-25-git-io-deprecation/

Replace the git.io link with its actual URL.

2022-04-28 09:23 UTC, rickstaa commented
LGTM. However, the git.io link will still be available as a read-only link. @anuraghazra, what do you think? Do you want to keep the old link since it still works or do you want to migrate to another URL shortener (e.g. https://bitly.com/ and https://short.io/?

2022-04-28 09:29 UTC, SukkaW commented
> I read the changelog, and it looks like the git.io link will still be available as a read-only link.

GitHub describes in a way that only git.io links in print documentation and research papers will retain services. Even if they have changed their mind, it is not guaranteed that the `git.io` will stop providing service in the future.

2022-04-28 10:10 UTC, rickstaa commented
@SukkaW Your right. I looked over those words. As I think there was a reason for shortening the URL, let's wait for @anuraghazra to decide on a new URL shortener.

2022-05-05 14:20 UTC, anuraghazra commented
@rickstaa short.io looks good but seems like I have to login right? Lets use this 

https://tinyurl.com/readme-stats

2022-05-05 14:21 UTC, anuraghazra commented
git.io was such a damn good URL tho. It's shame they deprecated it.

2022-05-07 08:16 UTC, rickstaa requested changes

2022-05-07 08:16 UTC, rickstaa commented on src/common/utils.js
> +    <text x="25" y="45" class="text">Something went wrong! file an issue at https://github.com/anuraghazra/github-readme-stats</text>
```suggestion
    <text x="25" y="45" class="text">Something went wrong! file an issue at https://tiny.one/readme-stats</text>
```

2022-05-07 08:16 UTC, rickstaa commented on src/common/utils.js
> +    <text x="25" y="45" class="text">Something went wrong! file an issue at https://github.com/anuraghazra/github-readme-stats</text>
@SukkaW I think this can be merged if the URL is changed.

2022-05-07 08:21 UTC, rickstaa commented
@anuraghazra Yea looks like short.io is a premium service. I can only create URLs if I already own a domain. `tiny.one/readme-stats` looks good. I, however, could not find the monthly click limit. The documentation states the following:

![image](https://user-images.githubusercontent.com/17570430/167245755-8d12734a-b940-414b-b45e-eb3a32ccf050.png)

I assume that the `-` means that URLs have unlimited link clicks, and the limits given on the premium plans are related to the tracking behaviour.

2022-05-16 08:04 UTC, rickstaa commented
@SukkaW Thanks again for your PR! I have merged it into the main branch.

2022-05-16 08:04 UTC, merged