Added a Gradient theme.
anuraghazra/github-readme-stats pull request #1918
Opened 2022-08-02 15:51 UTC by DylanDevelops

This is what it is supposed to look like:
<img width="535" alt="Screen Shot 2022-08-02 at 9 44 53 AM" src="https://user-images.githubusercontent.com/48571264/182416626-c9931938-1f78-4c00-8051-5477c5890444.png">

I'm not sure if I did the gradient right in the js file. I recreated this for my own repository but I just added the specifications and color straight into the url:

![Dylan's GitHub stats](https://github-readme-stats.vercel.app/api?username=DylanDevelops&show_icons=true&count_private=true&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff)

The url has: `&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff` to create the gradient. I am just not sure if the way I approached making it an actual theme is how you are supposed to make a gradient. I tried looking at others but no other themes had a gradient so I didn't have a reference to go off of. Let me know if its correct or how I would go about making the gradient work as an actual theme.

This theme is shown on the main readme file for this repository as an example but it used the specifications in the url and wasn't an actual theme.

2022-08-12 15:13 UTC, gabrielsav commented
Hi, can we change the gradient color? This is an awesome project!

2022-08-12 15:27 UTC, DylanDevelops commented
> Hi, can we change the gradient color? This is an awesome project!

Yes you can. If you take a look at my profile you can see the gradient that I made above. If you go into markdown on my page you can get the URL for it. Changing the color values in `&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff` this string of text in the url will do that. The gradient are the numbers next to 30. In my case, i'm making a gradient between e96443 and 904e95.

2022-10-02 13:40 UTC, rickstaa commented
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: gradient

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
          
### Gradient theme preview
          
          
          
- :x: Theme color property `bg_color` is not a valid hex color: <code>#30,e96443,904e95</code>.


          
>:x: Cannot create theme preview.

2022-10-02 13:40 UTC, rickstaa requested changes
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1918#issuecomment-1264646809) comment above for more information.

2022-10-02 14:26 UTC, rickstaa commented
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: gradient

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
          
### Gradient theme preview
          
          
          
- :x: Theme color property `bg_color` is not a valid hex color: <code>#30,e96443,904e95</code>.


          
>:x: Cannot create theme preview.

2022-10-02 15:29 UTC, rickstaa requested changes
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1918#issuecomment-1264646809) comment above for more information.

2022-10-18 14:35 UTC, rickstaa commented
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

2022-10-18 14:35 UTC, closed without merging