Accurate GitHub Dark Theme
anuraghazra/github-readme-stats pull request #1996
Opened 2022-09-03 19:46 UTC by intergrav

This adds a super accurate github dark theme. The other one is nice, but doesn't really fit as well as this one.

![image](https://user-images.githubusercontent.com/42325132/188285726-d71a454f-6f59-4094-9efc-10ae5ccdb2b4.png)

2022-10-02 13:39 UTC, rickstaa commented
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: accurate_github_dark

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Accurate_github_dark theme preview
        
        

        
title_color: <code>#c9d1d9</code> | icon_color: <code>#8b949e</code> | text_color: <code>#8b949e</code> | bg_color: <code>#0d1117</code> | border_color: <code>#30363d</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)

        
[![](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)

2022-10-02 13:39 UTC, rickstaa approved these changes

2022-10-02 14:19 UTC, rickstaa commented
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: accurate_github_dark

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Accurate_github_dark theme preview
        
        

        
title_color: <code>#c9d1d9</code> | icon_color: <code>#8b949e</code> | text_color: <code>#8b949e</code> | bg_color: <code>#0d1117</code> | border_color: <code>#30363d</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)

        
[![](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)

2022-10-02 14:19 UTC, rickstaa approved these changes

2022-10-02 14:20 UTC, rickstaa approved these changes

2022-10-02 14:20 UTC, rickstaa commented
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: accurate_github_dark

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Accurate_github_dark theme preview
        
        

        
title_color: <code>#c9d1d9</code> | icon_color: <code>#8b949e</code> | text_color: <code>#8b949e</code> | bg_color: <code>#0d1117</code> | border_color: <code>#30363d</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)

        
[![](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)

2022-10-02 14:24 UTC, rickstaa commented
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: accurate_github_dark

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Accurate_github_dark theme preview
        
        

        
title_color: <code>#c9d1d9</code> | icon_color: <code>#8b949e</code> | text_color: <code>#8b949e</code> | bg_color: <code>#0d1117</code> | border_color: <code>#30363d</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)

        
[![](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)

2022-10-02 14:24 UTC, rickstaa approved these changes

2022-10-02 15:28 UTC, rickstaa approved these changes

2023-03-05 02:06 UTC, Zo-Bro-23 commented
I like this theme. @rickstaa what do you think?

2023-03-05 09:41 UTC, rickstaa requested changes
**Something went wrong in the theme preview action:** `Not Found`

2023-03-05 09:42 UTC, rickstaa requested changes
**Something went wrong in the theme preview action:** `Not Found`

2023-03-05 09:56 UTC, rickstaa commented
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: accurate_github_dark

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Accurate_github_dark theme preview
        
        

        
title_color: <code>#c9d1d9</code> | icon_color: <code>#8b949e</code> | text_color: <code>#8b949e</code> | bg_color: <code>#0d1117</code> | border_color: <code>#30363d</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)

        
[![](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)

2023-03-05 09:56 UTC, rickstaa approved these changes

2023-03-05 09:57 UTC, rickstaa commented
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: accurate_github_dark

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Accurate_github_dark theme preview
        
        

        
title_color: <code>#c9d1d9</code> | icon_color: <code>#8b949e</code> | text_color: <code>#8b949e</code> | bg_color: <code>#0d1117</code> | border_color: <code>#30363d</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)

        
[![](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)

2023-03-05 09:57 UTC, rickstaa commented
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: accurate_github_dark

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Accurate_github_dark theme preview
        
        

        
title_color: <code>#c9d1d9</code> | icon_color: <code>#8b949e</code> | text_color: <code>#8b949e</code> | bg_color: <code>#0d1117</code> | border_color: <code>#30363d</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)

        
[![](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true)

2023-03-05 09:57 UTC, rickstaa approved these changes

2023-03-05 10:11 UTC, rickstaa commented
@Zo-Bro-23 I fixed the theme preview action again (see #2566). About this theme; I agree it is a nice theme. I however am curious why why @intergrav thinks this theme is a more accurate version of the `github_dark` theme we already have that was added in #758. I think that theme represents the GitHub Dark theme very well.

![image](https://user-images.githubusercontent.com/17570430/222954250-65ee47a8-79f4-4929-a1e4-25a32ce04124.png)

2023-03-05 10:21 UTC, Zo-Bro-23 commented
![](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c9d1d9&icon_color=8b949e&text_color=8b949e&bg_color=0d1117&border_color=30363d&show_icons=true&hide_border=true)

![](https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=github_dark&show_icons=true&hide_border=true)

Agreed. The text color just seems a bit weird because GitHub doesn't use that anywhere, but on closer inspection, the existing theme is good enough. Closing this for now.

2023-03-05 10:21 UTC, closed without merging

2023-03-05 16:55 UTC, intergrav commented
yeah it's fine, i hadn't realized you could set your own custom colors manually