Updated Readme.md
anuraghazra/github-readme-stats pull request #2389
Opened 2023-01-12 16:22 UTC by PSGitHubUser1

You have changed the URL of API so many people are facing problems. So I am doing this PR to update the readme file.

Now its correct.

2023-01-12 18:12 UTC, DvvCz commented
No, that is a different self-hosted instance of this.

2023-01-14 12:48 UTC, MitkoVtori requested changes
The problem is now fixed so everyone can return to the basic link. Rickstaa's fork won't be able to withstand a large amount of users.  Also, since this is rick's fork of this repo, there's absolutely no reason to change the link in the main readme.md

2023-01-14 12:48 UTC, MitkoVtori commented on readme.md
> +[![Anurag's GitHub stats](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=anuraghazra)](https://github.com/anuraghazra/github-readme-stats)
This is @rickstaa's (main collaborator) fork branch of this repository.

2023-01-14 20:32 UTC, rickstaa commented
> The problem is now fixed so everyone can return to the basic link. Rickstaa's fork won't be able to withstand a large amount of users. Also, since this is rick's fork of this repo, there's absolutely no reason to change the link in the main readme.md

@PSGitHubUser1 thanks for your pull request. @MitkoVtori's conclusion above is however correct my fork can only sustain a limited number of people at the same time due to GitHub's Graphql limits. 😅 Closing this for now.

2023-01-14 20:32 UTC, closed without merging