added user profile option to rankIcon
anuraghazra/github-readme-stats pull request #3145
Opened 2023-08-25 14:04 UTC by alex8obrien

- Adds the option for a users GitHub profile picture to be used as a rank icon
- I'm unable to test if this works, please feel free to clone this and update me with the results

closes #3128

2023-10-07 11:58 UTC, anuraghazra commented on src/common/icons.js
> +    case "profile":
Let's rename this to `avatar_image`

2023-10-07 12:05 UTC, anuraghazra commented on src/common/icons.js
> +const rankIcon = (username, rankIcon, rankLevel, percentile) => {
add the username param at the end instead of rearranging the params.

2023-10-07 12:09 UTC, anuraghazra commented
> I'm unable to test if this works, please feel free to clone this and update me with the results

Install the [vercel CLI ](https://vercel.com/docs/cli) and then just run `vercel dev` and open localhost:3000

2023-10-07 12:10 UTC, anuraghazra commented on src/cards/stats-card.js
> +          ${rankIcon(name, rank_icon, rank?.level, rank?.percentile)}
The githubusercontent requires the username, eg "anuraghazra" it cannot work with the name eg "Anurag Hazra", so you need to pass down the username.

2023-10-07 12:10 UTC, anuraghazra commented
Seems like the alignment is needed 
![image](https://github.com/anuraghazra/github-readme-stats/assets/35374649/91679301-e689-4da4-bf2f-8519397344d2)

2023-10-12 11:51 UTC, rickstaa requested changes
@alex8obrien see requested changes of @anuraghazra.

2024-05-11 12:38 UTC, closed without merging