[Fixes #3016] Show wakatime stats in percentage
anuraghazra/github-readme-stats pull request #3326
Opened 2023-10-05 15:07 UTC by ritik48

This pr fixes #3016 

#### Description

I have added an option to display wakatime stats in percentage.
User has to specify `display_format=percent` to show stats in percentage. If no value is proved then default is `time`

#### Screenshot

![percent](https://github.com/anuraghazra/github-readme-stats/assets/84488726/64c7e9d5-a10d-40bc-ac11-da51b2e23b3e)

2023-10-12 12:06 UTC, rickstaa requested changes

2023-10-12 12:06 UTC, rickstaa commented on src/cards/wakatime-card.js
> +                  ? language.percent.toString()
@ritik48, thanks for your pull request. For the percentage case, let's add the `%` suffix like is done in the language card. I will add the `hacktoberfest-accepted` label when that change is done 👍🏻.

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra)](https://github.com/anuraghazra/github-readme-stats)

2023-10-12 12:47 UTC, ritik48 commented
@rickstaa , I have added the percent sign. please review it.

2023-10-12 14:06 UTC, rickstaa commented on readme.md
> +* `display_format` - Option to display wakatime stats in percentage or time. Default `time`.
```suggestion
* `display_format` - Changes the wakatime stats display format (i.e. `time` or `percent`). Default `time`.
```

2023-10-12 14:10 UTC, rickstaa commented on readme.md
> +* `display_format` - Option to display wakatime stats in percentage or time. Default `time`.
Let's mention the options.

```suggestion
* `display_format` - Modifies the presentation style of WakaTime statistics. Choose between `time` to display time-based stats or `percent` to show percentages. The default is set to time.
```

2023-10-12 14:11 UTC, rickstaa requested changes
I think this pull request is done when you apply my suggestion 🚀.

2023-10-12 14:25 UTC, ritik48 commented
done 👍

2023-10-12 14:26 UTC, rickstaa approved these changes

2023-10-12 14:28 UTC, rickstaa commented
@ritik48 Amazing! Thanks again for your contribution. I attached the `hacktoberfest-accepted` label. This pull request will be merged when it has received enough upvotes (i.e. `+1`) and has been reviewed by a second team member 🚀.

2023-10-13 16:24 UTC, ritik48 commented
Thank you, @rickstaa! 😊 It's great to see the hacktoberfest-accepted label on my pull request. Hope it gets merged soon 🤞.

2023-10-20 19:50 UTC, qwerty541 requested changes
Hey, @ritik48! Thanks for your pull request and for your patience! Generally looks good, i'm okay to approve it when requested will be done.

2023-10-20 19:50 UTC, qwerty541 commented on api/wakatime.js
> +        display_format: display_format ? display_format : "",
Let's replace it with

```js
display_format,
```

2023-10-20 19:50 UTC, qwerty541 commented on readme.md
> +* `display_format` - Sets the WakaTime stats display format. Choose `time` to display time-based stats or `percent` to show percentages. The default is set to `time`.
Let's replace ``The default is set to `time`.`` with ``Default: `time`.``

2023-10-20 19:50 UTC, qwerty541 commented on src/cards/wakatime-card.js
> +                  : language.text,
Let's replace it with

```js
value:
  display_format === "percent"
    ? `${language.percent.toString()} %`
    : language.text,
```

2023-10-20 19:50 UTC, qwerty541 commented on src/cards/types.d.ts
> +  display_format: string
Let's replace it with

```js
display_format: "time" | "percent";
```

2023-10-20 19:50 UTC, qwerty541 commented on src/cards/wakatime-card.js
I also see that different rows have different float precision, it looks bad in my opinion. I think that precision should be equal everywhere.

![image](https://github.com/anuraghazra/github-readme-stats/assets/53787217/f784ff29-07bb-4fe5-9219-21da08404487)

2023-10-21 15:06 UTC, ritik48 commented
Hey @qwerty541 , please review it again. I have made the required changes.

2023-10-22 19:22 UTC, qwerty541 requested changes
> Hey @qwerty541 , please review it again. I have made the required changes.

@ritik48 Please make these two changes

2023-11-15 06:38 UTC, ritik48 commented on src/cards/wakatime-card.js
> +    display_format,
Hey @qwerty, all the changes have been made.

2023-11-15 06:38 UTC, ritik48 commented
Hey @qwerty, all the changes have been made.

2023-11-15 18:19 UTC, qwerty541 approved these changes
> Hey @qwerty, all the changes have been made.

Thanks, @ritik48! Currently this pull request looks good to me. I asked @rickstaa for reapproval and if he is okay with these changes we can merge it.

2023-11-16 11:51 UTC, rickstaa approved these changes
@qwerty541 I think we can merge this if tests are added 👍🏻.

2023-11-21 19:57 UTC, qwerty541 commented
> @qwerty541 I looked at the code, and it is clean. I think we can merge this if tests are added 👍🏻.

Hey, @ritik48! I'm curious about if you're up to cover this changes with test. 

@rickstaa Thanks, let me know what do you think about if i add test in future pull request. Maybe @ritik48 won't be able to add tests due to lack of time or experience.

2023-11-21 20:55 UTC, rickstaa commented
> > @qwerty541 I looked at the code, and it is clean. I think we can merge this if tests are added 👍🏻.
> 
> Hey, @ritik48! I'm curious about if you're up to cover this changes with test.
> 
> @rickstaa Thanks, let me know what do you think about if i add test in future pull request. Maybe @ritik48 won't be able to add tests due to lack of time or experience.

Fine with me. Thanks again for your work on GRS 🚀.

2023-11-23 04:41 UTC, ritik48 commented
@qwerty541 I don't have experience in adding tests, but I could do so with a little guidance.

2023-11-23 19:13 UTC, merged

2023-11-23 19:15 UTC, qwerty541 commented
> @qwerty541 I don't have experience in adding tests, but I could do so with a little guidance.

No problem, i will do it on my own later. I have resolved conflicts with master and merged pull request. Thanks for your contribution.