Added Hindi language support to README and translation.js
anuraghazra/github-readme-stats pull request #3985
Opened 2024-10-11 11:03 UTC by VaibhavVermaa16

- Updated README.md to include Hindi as one of the available locales.
- Modified src/translation.js to add all Hindi translations.
This PR is a part of Hacktoberfest 2024. Kindly review and merge. Thank you!

2024-10-11 11:16 UTC, Scutua commented
thank you very much

2025-02-22 18:06 UTC, eldrago4 requested changes

2025-09-18 18:59 UTC, qwerty541 approved these changes

2025-09-18 19:09 UTC, merged

2025-09-18 19:09 UTC, qwerty541 commented
Hello @VaibhavVermaa16 

Thank you for your contribution!