feat: number of languages param for top langs card
anuraghazra/github-readme-stats pull request #445
Opened 2020-09-09 19:16 UTC by scitronboy

Simply allows a user to specify how many languages to show on the top-langs card, between 1 and 10. Default is still 5.

Example here: [https://benjamins-readme-stats-bt29bovd9.vercel.app/api/top-langs/?username=scitronboy&layout=compact&theme=gruvbox&num_langs=10](https://benjamins-readme-stats-bt29bovd9.vercel.app/api/top-langs/?username=scitronboy&layout=compact&theme=gruvbox&num_langs=10)

Let me know if I need to add anything else to the PR.

2020-09-09 19:17 UTC, AryanBeezadhur approved these changes

2020-09-09 19:33 UTC, scitronboy commented
Update: there seems to be an issue with the bottom padding, I'll fix it

2020-09-09 21:03 UTC, scitronboy commented
Ok, it looks much better now

2020-09-10 15:27 UTC, AryanBeezadhur approved these changes
Looks good to me

2020-09-10 15:31 UTC, AryanBeezadhur requested changes
Actually, could you put some more padding between each line to improve readability?

![image](https://user-images.githubusercontent.com/34424160/92754640-f500f480-f382-11ea-88ac-abcfdf5471b3.png)

2020-09-10 18:29 UTC, anuraghazra requested changes

2020-09-10 18:29 UTC, anuraghazra commented on src/fetchers/top-languages-fetcher.js
> +  if (amount > 10 || amount < 1) throw Error("Invalid number of languages")
Don't need to throw error, just clamp it to the value between 1 & 5

use the clampValue function from the utils.js

```js
const {
  clampValue,
} = require("../src/common/utils");
```

2020-09-10 18:30 UTC, anuraghazra commented
Thanks @scitronboy this looks good, requested a minor change please look into it :)

2020-09-11 00:58 UTC, scitronboy commented
Ok, done. I clamped to the number 1, 10 with a default of 5. I have not changed the padding as Aryan suggested as it's the compact theme and I believe changing the padding would make it unnecessarily non-compact.

2020-09-12 13:13 UTC, anuraghazra approved these changes

2020-09-12 13:16 UTC, merged

2020-09-12 13:16 UTC, anuraghazra commented
Thanks for the PR @scitronboy