Card translations
anuraghazra/github-readme-stats pull request #509
Opened 2020-09-28 16:53 UTC by nthnchu

Add translations for the cards. Fixes #508.

- [x] Add translation functionality (with Google Translate)
- [x] Add tests and documentation
- [ ] Get translations verified or improved.
- [ ] Maybe move translations to one file (like `src/common/translations.js`) instead of in each `src/cards/*` file.

2020-09-28 18:22 UTC, lrusso96 commented
@anuraghazra You should merge this to a new branch, otherwise we cannot commit on it!
Alternatively, @nthnchu you should give the writing permission to your fork, so I can apply the changes before the PR to master branch.

2020-09-28 18:29 UTC, nthnchu commented
@lrusso96 You can fork my repo's card-translations branch and make a PR to that if I am correct.

2020-09-28 20:18 UTC, lrusso96 commented
> 
> 
> @lrusso96 You can fork my repo's card-translations branch and make a PR to that if I am correct.

Yep, you're right @nthnchu. I have opened a PR right now.

2020-10-01 11:15 UTC, schmelto requested changes

2020-10-01 11:15 UTC, schmelto commented on src/cards/stats-card.js
> +      de: "Insgesamt Sterne",
Sterne insgesamt

2020-10-01 11:15 UTC, schmelto commented on src/cards/stats-card.js
> +      de: "Total Commits",
Anzahl Commits

2020-10-01 11:15 UTC, schmelto commented on src/cards/stats-card.js
> +      de: "Gesamtausgaben",
Anzahl Issues

2020-10-01 11:15 UTC, schmelto commented on src/cards/wakatime-card.js
> +      de: "Wakatime Week Stats",
Wakatime Wochen Status

2020-10-02 07:29 UTC, anuraghazra commented on api/index.js
> +    lang,
I think `locale` would be a better name for the prop since lang would be confusing since we have top-langs cards too.

2020-10-02 08:41 UTC, anuraghazra commented
Hi @nthnchu thanks for the awesome work.

I've further improved the code by adding a I18n.js class to handle the internationalization, & also extracted all the translations to translation.js file for better colocation.

Feel free to improve on it & give feedbacks if you have any.

2020-10-02 12:06 UTC, nthnchu commented
@anuraghazra I just changed it so you don't have to reference `translations.repocard["repocard.archived"]` and instead can do `translations.repocard.archived` (with the real variable names, I forget what they are called)

2020-10-02 12:18 UTC, schmelto requested changes

2020-10-02 12:18 UTC, schmelto commented on src/translations.js
> +    de: "Keine Codierungsaktivität diese Woche",
de: "Keine Aktivitäten in dieser Woche ",

2020-10-02 13:03 UTC, anuraghazra commented
> @anuraghazra I just changed it so you don't have to reference `translations.repocard["repocard.archived"]` and instead can do `translations.repocard.archived` (with the real variable names, I forget what they are called)

Actually it was totally intentional.

So that we have some context of which translation we are fetching just by looking at the `i18n.t("repocard.title")`  code.

2020-10-02 13:10 UTC, nthnchu commented
> > @anuraghazra I just changed it so you don't have to reference `translations.repocard["repocard.archived"]` and instead can do `translations.repocard.archived` (with the real variable names, I forget what they are called)
> 
> Actually it was totally intentional.
> 
> So that we have some context of which translation we are fetching just by looking at the `i18n.t("repocard.title")` code.

Ah ok that makes sense. I'll revert my commit

2020-10-03 15:25 UTC, anuraghazra commented
The translation code looks good but there is a few design issues with the card, because of the new languages, the text width is increased and the text is overlapping with the stats.

2020-10-04 08:04 UTC, anuraghazra commented
Okay @nthnchu i think this is ready, now people can improve the translations on separate PRs

2020-10-04 08:04 UTC, anuraghazra commented
Thanks for this feature @nthnchu & all of you who helped translating & will be going to help with the translation.

2020-10-04 08:05 UTC, merged