Update readme.cn about note, wakatime card
anuraghazra/github-readme-stats pull request #658
Opened 2020-11-20 07:00 UTC by Olvi73

GitHub Stats Card first note translation
Wakatime Card Exclusive Options translation

2020-11-20 10:53 UTC, Olvi73 commented
I commit a full match of chinese version to main readme.md

2020-12-09 01:05 UTC, Hephaest approved these changes
Great job!

2021-01-01 22:25 UTC, liyishuai requested changes
Further localization, including terms and punctuations.

2021-01-01 22:25 UTC, liyishuai commented on docs/readme_cn.md
> +Rank 值是通过你的 commits, contributions, issues, stars, pull requests, followers, 以及拥有的 repositories,
```suggestion
_注：可用的等级有 S+（前 1%）、S（前 25%）、A++（前 45%）、A+（前 60%）以及 B+（其余所有人）。
等级由提交数（commits）、参与项目数（contributions）、提出问题数（issues）、获标星数（stars）、提案数（pull requests）、关注者（followers）、仓库数（repositories）决定，
```

2021-01-01 22:25 UTC, liyishuai commented on docs/readme_cn.md
> +- `disable_animations` - 禁用卡片中的所有动画 _(boolean)_
中文夹用英文应使用全角括号，下同。
此遗留问题，可另行修正。

2021-01-01 22:25 UTC, liyishuai commented on docs/readme_cn.md
> +> 你能使用[urlencoder.org](https://www.urlencoder.org/) 来帮助你自动转换。
```suggestion
> 自动转换编码，可使用[urlencoder.org](https://www.urlencoder.org/)。
```

2021-01-01 22:25 UTC, liyishuai commented on docs/readme_cn.md
> +你可以使用 `&langs_count=` 选项来增加或减少卡片上显示的语言数量。有效值介于1和10(包含10)之间的整数，默认值为5。
```suggestion
你可以使用 `&langs_count=` 选项来增加或减少卡片上显示的语言数量。有效值为整数从1到10（含），默认值为5。
```

2021-02-07 23:14 UTC, closed without merging