Improve Chinese Translation
anuraghazra/github-readme-stats pull request #836
Opened 2021-01-27 07:00 UTC by xiaopangju

According to https://docs.github.com/cn/github/collaborating-with-issues-and-pull-requests , change "提案" into "拉取请求".

2021-01-27 07:05 UTC, xiaopangju commented
@anuraghazra Why are there two mistakes here?
![图片](https://user-images.githubusercontent.com/56964531/105955361-1f90e700-60b1-11eb-8bb7-197fb5c9d275.png)

2021-01-27 07:11 UTC, xiaopangju commented
@liyishuai Can you help me review this? Thanks!

2021-01-27 09:03 UTC, liyishuai requested changes

2021-01-27 09:03 UTC, liyishuai commented on src/translations.js
> +      cn: "拉取请求数（PR）",
如不知英文pull request，见到”拉取请求数“一词会理解为“number of requests pulled”，故主张激进地意译为“提案”。特别是在有英文标注的情况下，没有直译的必要。

2021-01-27 13:21 UTC, xiaopangju commented on src/translations.js
> +      cn: "拉取请求数（PR）",
那么您认为关于这个可以保留原文吗？但这样的话，就与上面和下面的翻译风格（对于特定名词中文译文加上英文原文）不一样了。感觉很难取舍

2021-01-27 18:49 UTC, liyishuai approved these changes
@anuraghazra While I have linguistic concerns, the changes here are coherent with GitHub documentations. Worth merging now and revising after GitHub documents changed.

2021-01-27 18:49 UTC, liyishuai commented on src/translations.js
> +      cn: "拉取请求数（PR）",
目前统一的体例是意译+原文。鉴于你提出的改动与官方文档一致，可先采纳，待官方文档改进后再另行修订。

2021-01-29 19:43 UTC, antoniosuperba commented on src/translations.js
> +      cn: "拉取请求数（PR）",
https://p2guides.wordpress.com/

2021-03-02 14:02 UTC, xiaopangju commented
please keep open

2021-03-07 16:33 UTC, anuraghazra commented
Thanks for the changes @xiaopangju and @liyishuai for review

2021-03-07 16:33 UTC, merged