add corner rounding parameter so we can make square cards
anuraghazra/github-readme-stats pull request #845
Opened 2021-01-29 18:19 UTC by tcheinen

Cards are rounded by default which looks kinda ugly when you have two adjacent cards with a dark theme and a light background.  I added support for a parameter which allows users to control the rounding used by the card (and had it default to the original 4.5).  I added implementation, tests, and readme docs but feel free to ping me if I missed anything.  

![image](https://user-images.githubusercontent.com/1759360/106311922-833f1f80-622b-11eb-8f13-6bb922cee7ac.png)

2021-02-08 07:32 UTC, filiptronicek requested changes
Many thanks for the contribution, @tcheinen, I just have one thing that I think could be tweaked. As you can see [here](https://github.com/anuraghazra/github-readme-stats#stats-card-exclusive-options), all the parameters are pretty memorable and easily self-explainable. I think it would be better to name it something like `border_radius` or `rounding`.

2021-02-08 16:17 UTC, tcheinen commented
makes sense!  I renamed it to border_radius

2021-02-08 16:24 UTC, filiptronicek approved these changes
LGTM ✅

2021-03-07 16:53 UTC, anuraghazra commented
This looks great @tcheinen sorry for the delay.

2021-03-07 16:53 UTC, merged