Update License Year
anuraghazra/github-readme-stats pull request #904
Opened 2021-02-23 23:52 UTC by MrBrain295

2020 to 2021

2021-02-27 20:12 UTC, SideFli commented
ok. make sense to me

2021-03-01 10:31 UTC, mmvanheusden requested changes
Maybe change (c) to ©

2021-03-01 10:31 UTC, mmvanheusden commented on LICENSE
> +Copyright (c) 2021 Anurag Hazra
Maybe change (c) to ©

2021-03-01 23:35 UTC, MrBrain295 commented on LICENSE
> +Copyright (c) 2021 Anurag Hazra
Ok

2021-03-05 14:54 UTC, xiaopangju approved these changes

2021-03-07 16:27 UTC, merged